### ISSUE TITLE
Rich display of sf objects in console requires geojsonio package

### ISSUE THREAD

**Issue by aridf** [scottyhq/jhub-rstudio#10]
Currently the sf package on the server enables working with sf objects, when printing these objects to console I receive the following error: 

`
ERROR while rich displaying an object: Error in loadNamespace(name): there is no package called ‘geojsonio’
`

It still prints the sf, but less neatly than I am used to. Will try to add geojsonio to environment.yml and submit new PR on the sf branch to fix

**Comment by scottyhq** [comment]
closed by #11
