### ISSUE TITLE
Removed eiCompare also removes dependencies

### ISSUE THREAD

**Issue by aridf** [scottyhq/jhub-rstudio#15]
Looks like a recent PR removed eiCompare from environment.yml. This is probably to enable us to install other versions. However, now I'm having trouble using `devtools::load_all()` within my local repo because eiCompare's dependencies are not installed.

```
> devtools::load_all()
Loading eiCompare
Error: Dependency package(s) 'wru' not available.
```

Will try a PR to add all of the dependencies.

**Comment by scottyhq** [comment]
> This is probably to enable us to install other versions. 

@aridf , yes, this was avoid confusion by having people explicitly install a specific version. For example if you run `devtools::install_github('DSSG-eiCompare/eiCompare@master')` 

Whatever dependencies are missing get installed:
```
Using github PAT from envvar GITHUB_PAT

Downloading GitHub repo DSSG-eiCompare/eiCompare@master

Rcpp    (1.0.4.6 -> 1.0.5 ) [CRAN]
sys     (3.3     -> 3.4   ) [CRAN]
tmvnsim (NA      -> 1.0-2 ) [CRAN]
coda    (NA      -> 0.19-3) [CRAN]
mnormt  (1.5-7   -> 2.0.1 ) [CRAN]
eiPack  (NA      -> 0.2-1 ) [CRAN]
mcmcse  (NA      -> 1.4-1 ) [CRAN]
wru     (NA      -> 0.1-9 ) [CRAN]
ei      (NA      -> 1.3-3 ) [CRAN]
Installing 9 packages: Rcpp, sys, tmvnsim, coda, mnormt, eiPack, mcmcse, wru, ei

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

✔  checking for file ‘/tmp/Rtmp5SryO4/remotes5d85be90a12/DSSG-eiCompare-eiCompare-7a26eaf25a924d6eefb6adbf60326e3a11366e9b/DESCRIPTION’ (349ms)
─  preparing ‘eiCompare’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘eiCompare_2.4.tar.gz’
```

You're right we could speed this up by pre-installing dependencies

**Comment by aridf** [comment]
Ah, okay awesome I will install that way. Thanks Scott.

**Comment by aridf** [comment]
This was resolved by install_github
