### ISSUE TITLE
sf still not loading with library()

### ISSUE THREAD

**Issue by aridf** [scottyhq/jhub-rstudio#9]
@scottyhq I have added sf to environment.yml but it seems like the server still cannot find it when I run library(sf) in either a jupyter notebook or Rstudio

https://github.com/DSSG-eiCompare/jhub-rstudio/blob/1a02f36b6fc6948b4905b8cc2a588be4e44d77c2/binder/environment.yml#L39-L41

**Comment by scottyhq** [comment]
@aridf - yeah, an inconvenience of the current setup is that I need to interrupt everyone and restart the server for you to get the new image. In the meantime you can try to open a terminal and run `conda install r-sf` and it should load in your current environment. Probably you'll have to 'restart kernel' in jupyter or 'restart R session' in rstudio...

**Comment by aridf** [comment]
Works great now!
